# Generated by Django 4.2 on 2023-04-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
